ALTER TABLE "Vehicle"
ADD COLUMN "brand" TEXT NOT NULL DEFAULT 'Araucana',
ADD COLUMN "model" TEXT NOT NULL DEFAULT 'Operativo',
ADD COLUMN "licensePlate" TEXT,
ADD COLUMN "templateKey" TEXT,
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
