import Link from "next/link";
import type { CSSProperties } from "react";
import { HistoricalMap } from "@/components/historical-map";
import { ServicesGrid } from "@/components/services-grid";
import { SiteFooter } from "@/components/site-footer";
import { listPublicRoutes } from "@/lib/booking/repository";
import laninWinter from "../../lanin-invierno.jpeg";
import laninSummer from "../../lanin-verano.jpeg";

export const revalidate = 300;
const whatsappUrl = "https://wa.me/5492944649049";

function todayDateKey() {
  return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Salta", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
}

export default async function HomePage() {
  const routes = await listPublicRoutes();
  const heroStyle = { "--hero-image": `url(${laninWinter.src})` } as CSSProperties;
  const finalStyle = { "--final-image": `url(${laninSummer.src})` } as CSSProperties;
  const destinations = [["San Martín de los Andes", "Lagos, bosque y montaña"], ["Chapelco", "Nieve y experiencias de altura"], ["Lago Hermoso", "Un refugio en la cordillera"], ["Villa La Angostura", "Ruta, lago y bosque"]];
  return <>
    <section className="new-hero" style={heroStyle}><div className="new-hero-inner"><div className="new-hero-copy"><p className="eyebrow eyebrow-light">La Araucana · Patagonia Argentina</p><h1>Mucho más que<br /><em>un traslado.</em></h1><p className="new-hero-lead">Llegá a Patagonia. Nosotros nos ocupamos del camino.</p><p className="new-hero-detail">Traslados desde y hacia Chapelco, excursiones, servicios privados y soluciones para grupos.</p><div className="hero-actions"><Link className="accent-button" href="/rutas" prefetch={true}>Reservar mi traslado <span>↗</span></Link><a className="hero-whatsapp-link" href={whatsappUrl} target="_blank" rel="noreferrer">Hablar por WhatsApp <span>↗</span></a></div></div><div className="new-hero-badge"><span className="hero-note-dot" /> Experiencia local <strong>desde 2009</strong></div></div></section>
    <main>
      <section className="page-shell new-section service-showcase" id="servicios"><div className="section-head"><div><p className="eyebrow">Elegí cómo viajar</p><h2 className="section-title">Tu viaje empieza<br /><span>acá.</span></h2></div><p className="lead section-intro">Una forma simple, cuidada y cómoda de descubrir la Patagonia. Elegí el servicio que necesitás y nosotros nos ocupamos del resto.</p></div><ServicesGrid services={[{ number: "01", title: "Traslados aeropuerto", text: "Chapelco ↔ San Martín de los Andes y otros destinos.", href: "#chapelco", tone: "service-green" }, { number: "02", title: "Traslados privados", text: "Puerta a puerta para viajar con comodidad y flexibilidad.", href: whatsappUrl, tone: "service-snow" }, { number: "03", title: "Excursiones y destinos", text: "Movilidad para conocer los paisajes más increíbles.", href: "#destinos", tone: "service-sky" }, { number: "04", title: "Grupos y empresas", text: "Soluciones para colegios, eventos, equipos y contingentes.", href: "#contacto", tone: "service-red" }]} /></section>
      <section className="chapelco-section page-shell" id="chapelco"><div className="chapelco-copy"><p className="eyebrow eyebrow-light">Servicio destacado</p><h2>Del aeropuerto<br />a tu destino.<br /><em>Sin complicaciones.</em></h2><p>Llegás a Chapelco y nosotros nos ocupamos del resto. Traslados cómodos, seguros y coordinados para que empieces tu viaje desde el primer momento.</p><div className="route-pills"><span>Chapelco <b>→</b> San Martín</span><span>San Martín <b>→</b> Chapelco</span></div><Link className="cream-button" href="/rutas" prefetch={true}>Reservar traslado <span>↗</span></Link></div><form className="chapelco-form" action="/rutas" method="get"><div className="booking-card-top"><span>Buscá tu traslado</span><span className="status-dot">● Disponible</span></div><label><small>Origen</small><select name="from" defaultValue=""><option value="">Elegí un origen</option>{Array.from(new Set(routes.map((route) => route.from))).map((origin) => <option value={origin} key={origin}>{origin}</option>)}</select></label><label><small>Destino</small><select name="to" defaultValue=""><option value="">Elegí un destino</option>{Array.from(new Set(routes.map((route) => route.to))).map((destination) => <option value={destination} key={destination}>{destination}</option>)}</select></label><label><small>Fecha</small><input type="date" name="date" defaultValue={todayDateKey()} /></label><button className="accent-button" type="submit">Ver horarios ↗</button></form></section>
      <section className="page-shell new-section destination-section" id="destinos"><div className="section-head"><div><p className="eyebrow">Nuestros destinos</p><h2 className="section-title">Paisajes que<br /><span>quedan.</span></h2></div><p className="lead section-intro">Conocemos cada curva, cada lago y cada camino. Consultá tu traslado al destino que quieras descubrir.</p></div><div className="destination-grid">{destinations.map(([title, detail], index) => <a className={`destination-card destination-${index + 1}`} href={whatsappUrl} target="_blank" rel="noreferrer" key={title}><span className="destination-number">0{index + 1}</span><span className="destination-shade" /><div><small>{detail}</small><h3>{title}</h3><span className="destination-link">Consultar traslado ↗</span></div></a>)}</div></section>
      <section className="promise-section page-shell" id="nosotros"><div className="promise-image"><img src="/story-araucana.png" alt="Unidad de La Araucana preparada para viajar" /></div><div className="promise-copy"><p className="eyebrow">Mucho más que un traslado</p><h2 className="section-title">Viajar bien también<br /><span>es parte del viaje.</span></h2><p className="lead">En La Araucana entendemos que el viaje empieza mucho antes de llegar al destino.</p><p>Por eso cuidamos cada detalle: coordinación, puntualidad, confort y atención. Queremos que subas y sientas: <strong>“Estoy en buenas manos.”</strong></p><div className="trust-list"><span>Puntualidad</span><span>Coordinación</span><span>Confort</span><span>Atención personalizada</span></div></div></section>
      <section className="fleet-section page-shell"><div><p className="eyebrow">Flota</p><h2 className="section-title">Preparada para<br /><span>Patagonia.</span></h2><p className="lead">Unidades impecables, seguras y listas para acompañarte en cada recorrido.</p><a className="text-link" href={whatsappUrl} target="_blank" rel="noreferrer">Consultar disponibilidad ↗</a></div><div className="fleet-photo-card"><img src="/fleet-araucana.webp" alt="Paisaje nevado de la cordillera patagónica" /><div className="fleet-photo-caption"><span>La ruta también es parte del viaje</span><strong>Tu próxima aventura<br />viaja cómoda.</strong></div></div></section>
      <section className="page-shell new-section map-section" id="mapa"><div className="section-head"><div><p className="eyebrow">Área de operación</p><h2 className="section-title">Patagonia para<br /><span>descubrir.</span></h2></div><p className="lead section-intro">Explorá algunos de los lugares donde llegamos. Mové el mapa y encontrá tu próximo destino.</p></div><HistoricalMap /></section>
      <section className="trust-band page-shell"><div className="trust-badge">✓</div><div><p className="eyebrow">Respaldo y experiencia</p><h2>Una atención cercana para viajar con tranquilidad.</h2></div><p>Empresa habilitada como Agencia de Turismo Estudiantil.</p></section>
      <section className="final-image" style={finalStyle}><div><p className="eyebrow eyebrow-light">Patagonia te espera</p><h2>El viaje<br />es <em>ahora.</em></h2><Link className="cream-button" href="/rutas" prefetch={true}>Empezá a viajar <span>↗</span></Link></div></section>
      <section className="contact-section page-shell" id="contacto"><div className="contact-copy"><p className="eyebrow">Contacto</p><h2 className="section-title">¿A dónde vas?<br /><span>Nosotros te llevamos.</span></h2><p className="lead">Estamos para ayudarte a organizar tu próximo traslado.</p><p className="address">Mariano Moreno 829<br />San Martín de los Andes<br />Todos los días · 8:30 a 21:00 hs</p></div><div className="contact-card"><small>Hablemos</small><a href={whatsappUrl} target="_blank" rel="noreferrer" className="contact-whatsapp">WhatsApp +54 9 2944 64-9049 ↗</a><a href="tel:+542972420285">02972 420285</a><a href="mailto:info@araucana.com.ar">info@araucana.com.ar</a><div className="socials"><a href="https://www.instagram.com/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.google.com/maps/search/?api=1&query=Mariano+Moreno+829+San+Martin+de+los+Andes" target="_blank" rel="noreferrer">Cómo llegar ↗</a></div></div></section>
    </main>
    <a className="floating-whatsapp" href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="Hablar por WhatsApp"><span className="whatsapp-logo" aria-hidden="true"><svg viewBox="0 0 32 32" role="img"><circle cx="16" cy="16" r="16" fill="currentColor" /><path fill="#fff" d="M22.3 18.7c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-1 1.2-.2.2-.4.2-.7.1-.3-.2-1.3-.5-2.5-1.6-.9-.8-1.6-1.8-1.8-2.1-.2-.3 0-.5.1-.7l.5-.6c.2-.2.2-.4.3-.6.1-.2 0-.5 0-.7-.1-.2-.7-1.7-.9-2.3-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.3-1.1 1.1-1.1 2.7 0 1.6 1.1 3.1 1.3 3.3.2.2 2.2 3.4 5.4 4.7.8.3 1.4.5 1.9.6.8.2 1.5.2 2 .1.6-.1 1.8-.7 2-1.4.3-.7.3-1.3.2-1.4-.1-.2-.3-.3-.6-.4ZM16 6.3a9.7 9.7 0 0 0-8.3 14.7L6.4 26l5.1-1.3A9.7 9.7 0 1 0 16 6.3Zm0 17.8c-1.6 0-3.1-.4-4.5-1.2l-.3-.2-3 .8.8-2.9-.2-.3a8.1 8.1 0 1 1 7.2 3.8Z" /></svg></span></a><SiteFooter />
  </>;
}
